spring.application.name=Assignment1

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.audio.transcription.model=gpt-4o-transcribe

spring.ai.openai.audio.transcription.temperature=0

server.shutdown=graceful

spring.lifecycle.timeout-per-shutdown-phase=20s
